spring:
  application:
    name: sparkmysql
  
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085

spark:
  app-name: SparkMySQLApp
  master: local[*]
  mysql:
    url: jdbc:mysql://localhost:3306/employee_db
    user: root
    password: root
    driver: com.mysql.cj.jdbc.Driver